### PR TITLE
Stop if /dev is not a bind mount with loopback

### LINKED ISSUE #352: Requires `-v /dev:/dev` for reliable loopback
Sometimes I see:

```
DEBUG exec: "losetup" "--show" "-P" "--find" "/output/bootc.raw"
losetup: /output/bootc.raw: failed to set up loop device: No such file or directory
```

I think we may need to wait on udev on the host.

### PR DESCRIPTION
**Pull request by bcrochet**
At container start, /dev is snapshotted, so any new device files
don't get added unless /dev is bindmounted in. For now, check that
/dev is the same as the host's /dev via fsid. If they differ, it
means that /dev is not bindmounted.

Fixes #352

### CODE REVIEW

**Comment by bcrochet** [comment]
What's here now is the "quick and dirty" fix. If this is sufficient for the time being, I'd say it's good-to-go. I'm currently looking at cleaning up some of the mount code (there are lots of places that it's done now). Some deduplication is in order.

**Comment by bcrochet** [comment]
> What's here now is the "quick and dirty" fix. If this is sufficient for the time being, I'd say it's good-to-go. I'm currently looking at cleaning up some of the mount code (there are lots of places that it's done now). Some deduplication is in order.

Moved around a little bit. I've added it as an additional commit. Will collapse before merging.

File: lib/src/mount.rs [hunk 1]
```diff
@@ -57,3 +57,19 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
...
 }
+
+// Ensure the `/dev` directory exists.
+fn ensure_mountpoint(target: &str) -> Result<()> {
+    std::fs::create_dir_all(target)?;
+    Ok(())
+}
+
+/// General mount that also checks that mount path exists
+pub(crate) fn ensure_mount(dev: &str, target: &str, fstype: &str) -> Result<()> {
```
Comment (cgwalters) [inline lib/src/mount.rs:68]: Minor/optional: Function with especially >2 parameters all of the same type can be easy to call with the wrong arguments.  We could change `fstype` to be an `enum FilesystemType { Devtmpfs }` for example.

Another thing to do (which can be combined) is to use `&Utf8Path` here instead of `&str` which expresses semantically that it's a path.

File: lib/src/mount.rs [hunk 2]
```diff
@@ -57,3 +57,19 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
...
     )
 }
+
+// Ensure the `/dev` directory exists.
+fn ensure_mountpoint(target: &str) -> Result<()> {
+    std::fs::create_dir_all(target)?;
+    Ok(())
+}
+
+/// General mount that also checks that mount path exists
```
Comment (cgwalters) [inline lib/src/mount.rs:67]:
```suggestion
/// Create the target directory if it doesn't exist, then mount the specified filesystem
```

(It doesn't "check", it "ensures" or so right?)

File: lib/src/mount.rs [hunk 3]
```diff
@@ -57,3 +57,19 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
         [dev, target.as_str()],
     )
 }
+
+// Ensure the `/dev` directory exists.
```
Comment (cgwalters) [inline lib/src/mount.rs:61]: This docstring looks wrong (and function docstrings need `///`)

File: lib/src/mount.rs [hunk 4]
```diff
@@ -57,3 +57,19 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
...
+fn ensure_mountpoint(target: &str) -> Result<()> {
+    std::fs::create_dir_all(target)?;
+    Ok(())
```
Comment (cgwalters) [inline lib/src/mount.rs:64]: I'm not totally sure this function carries its weight over simply inlining the `std::fs::create_dir_all(target)` into callers?

File: lib/src/mount.rs [hunk 5]
```diff
@@ -57,3 +57,19 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
...
+}
+
+/// General mount that also checks that mount path exists
+pub(crate) fn ensure_mount(dev: &str, target: &str, fstype: &str) -> Result<()> {
+    ensure_mountpoint(target)?;
```
Comment (cgwalters) [inline lib/src/mount.rs:69]: I had actually expected this call to be handling *idempotence* - i.e. we don't do the mount if the target is already mounted with the expected type.

The current docs gained a `-v /dev:/dev` recommendation for this reason, and I think we don't want to overmount it.

File: lib/src/blockdev.rs [hunk 6]
```diff
@@ -80,9 +85,17 @@ pub(crate) struct LoopbackDevice {
...
+fn ensure_dev_mounted() -> Result<()> {
+    crate::mount::ensure_mount(DEVTMPFS, DEV_MOUNT_POINT, DEVTMPFS)?;
+    Ok(())
+}
+
 impl LoopbackDevice {
     // Create a new loopback block device targeting the provided file path.
     pub(crate) fn new(path: &Path) -> Result<Self> {
+        // Ensure /dev exists and is mounted
+        ensure_dev_mounted()?;
```
Comment (cgwalters) [inline lib/src/blockdev.rs:98]: Optional: I'm OK with this, although there's some action-at-a-distance here and arguably we should be doing this very early on in the callers instead (and we could add an assertion here that it's been done).

**Review by cgwalters — COMMENTED** [review]
Thanks for working on this, our saga of filesystem mounts will probably continue for a while :smile:

File: lib/src/mount.rs (hunk 1 above)
Comment (cgwalters) [reply lib/src/mount.rs:68]: I went to look at [the rustix mount API](https://docs.rs/rustix/latest/rustix/mount/fn.mount.html) and saw a "Fs" parameter which I thought would be an enum like this, but it's actually just a generic bytestring (ultimately of course we don't want to *need* to change rustix/glibc when a new Linux filesystem appears so I guess it has to be just a string, but in this code nothing stops us from having an enum, feels like it would make sense)

**Comment by bcrochet** [comment]
I got trigger-happy with pushing. I still need to address the idempotency part.

**Comment by cgwalters** [comment]
Per discussion I think there are two paths here:

- Recommend `-v /dev:/dev` and for now *error out* if we're doing loopback and `/dev` is not the real system `/dev` (I think we could statx `/dev` versus `/proc/1/root/dev` and compare `stx_mnt_id` ?)

Other two paths are:

- The re-exec flow to force on `/dev` binding
- https://github.com/containers/bootc/issues/380#issuecomment-1986526854 to do dynamic remounts from host

**Comment by bcrochet** [comment]
> Per discussion I think simplest may be:
> 
> * Recommend `-v /dev:/dev` and for now _error out_ if we're doing loopback and `/dev` is not the real system `/dev` (I think we could statx `/dev` versus `/proc/1/root/dev` and compare `stx_mnt_id` ?)
> 
> Other two paths are:
> 
> * The re-exec flow to force on `/dev` binding
> * [Add `install alongside` #380 (comment)](https://github.com/containers/bootc/issues/380#issuecomment-1986526854) to do dynamic remounts from host

Agreed. Let's start with the error out and suggestion of -v /dev:/dev.

**Comment by cgwalters** [comment]
Comparing the mounts I think can be done via https://docs.rs/rustix/latest/rustix/fs/fn.statx.html

**Comment by bcrochet** [comment]
So, this code works as expected, however for some reason once `-v /dev:/dev` is added, the losetup is still failing for me locally. Investigating...

File: lib/src/mount.rs [hunk 7]
```diff
@@ -57,3 +57,24 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
         [dev, target.as_str()],
     )
 }
+
+/// If the fsid of the passed path matches the fsid of the same path rooted
+/// at /proc/1/root, it is assumed that these are indeed the same mounted
+/// filesystem between container and host.
+/// Path *should* not include a leading '/'. It will be stripped.
```
Comment (cgwalters) [inline lib/src/mount.rs]: I'm fine with this as is but it actually seems simpler to me to just let it be an absolute path (because in fact we are calling it that way just above :smile: ) and rely on the `strip_prefix` to make it relative for the hostpath.

Comment (jeckersb) [inline lib/src/mount.rs:64]: The emphasis is misleading here and confused me the first time I read through it.  I think "should *not*" is preferable (or maybe "*should not*").

**Comment by bcrochet** [comment]
> So, this code works as expected, however for some reason once `-v /dev:/dev` is added, the losetup is still failing for me locally. Investigating...

It works on a centos VM, but not on a fedora host directly. That's the only diff I have so far.

File: lib/src/install.rs [hunk 8]
```diff
@@ -1177,6 +1177,9 @@ pub(crate) async fn install_to_disk(mut opts: InstallToDiskOpts) -> Result<()> {
                 block_opts.device
             );
         }
+        if !crate::mount::is_same_as_host(Utf8Path::new("/dev"))? {
+            anyhow::bail!("Add `-v /dev:/dev` to `podman` when using --via-loopback");
```
Comment (cgwalters) [inline lib/src/install.rs:1181]: How about "Loopback mounts (--via-loopback) require host devices (`-v /dev:/dev`)" ?

File: lib/src/mount.rs [hunk 9]
```diff
@@ -57,3 +57,24 @@ pub(crate) fn mount(dev: &str, target: &Utf8Path) -> Result<()> {
         [dev, target.as_str()],
     )
 }
+
+/// If the fsid of the passed path matches the fsid of the same path rooted
+/// at /proc/1/root, it is assumed that these are indeed the same mounted
+/// filesystem between container and host.
+/// Path *should not* include a leading '/'. It will be stripped.
```
Comment (cgwalters) [inline lib/src/mount.rs:64]: But we do pass a leading `/` in the single caller :smile: 

How about let's just say it should be absolute and rely on the `strip_prefix`  below.

Comment (bcrochet) [reply lib/src/mount.rs:64]: Good point.

**Review by cgwalters — APPROVED** [review]
